### ISSUE TITLE
Crash when tap on a video to watch

### ISSUE THREAD

**Issue by CySxL** [PoomSmart/YouMute#1]
Crash logs from Cr4shed :
https://pastebin.com/HM6QH5E7

```
Date: 2022/11/29 上午2:20
Process: YouTube
Bundle id: com.google.ios.youtube
Device: iPhone 11 Pro Max, iOS 14.8
Bundle version: 17.46.4

Exception type: NSInvalidArgumentException
Reason: -[__NSFrozenArrayM insertObject:atIndex:]: unrecognized selector sent to instance 0x282289260
Culprit: YouMute.dylib

Call stack:
0   CoreFoundation                      0x0000000198ac6dd4 0x19899d000 + 0x129dc0        // __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001ad61e7a8 0x1ad5f6000 + 0x287a8         // objc_exception_throw
2   CoreFoundation                      0x00000001989ca2d0 0x19899d000 + 0x2d2d0         // -[NSOrderedSet initWithSet:copyItems:]
3   CoreFoundation                      0x0000000198ac9918 0x19899d000 + 0x12c918        // ___forwarding___
4   CoreFoundation                      0x0000000198acbc10 0x19899d000 + 0x12ec10        // _CF_forwarding_prep_0
5   YouMute.dylib                       0x00000001128bf750 0x1128b8000 + 0x7750          // func_7710
6   YouMute.dylib                       0x00000001128bf214 0x1128b8000 + 0x7214          // func_71e0
7   YouTube                             0x0000000100ca3c34 0x1006c0000 + 0x5e3c34        // func_5e3650
8   YTKPlus.dylib                       0x00000001103beabc 0x110398000 + 0x26abc         // _logos_method$gHideBackButtonShadowsInOverlay$YTMainAppControlsOverlayView$layoutSubviews(YTMainAppControlsOverlayView*, objc_selector*)
9   YTKPlus.dylib                       0x00000001103bf140 0x110398000 + 0x27140         // _logos_method$gHideCastButtonOverlay$YTMainAppControlsOverlayView$layoutSubviews(YTMainAppControlsOverlayView*, objc_selector*)
10  uYou.dylib                          0x0000000113accd84 0x1128ec000 + 0x11e0d84       // func_11e0d68
11  UIKitCore                           0x000000019b9f8be4 0x19a8ed000 + 0x110bbe4       // -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
12  QuartzCore                          0x000000019be7f670 0x19bd18000 + 0x167670        // -[CALayer layoutSublayers]
13  QuartzCore                          0x000000019be7fb54 0x19bd18000 + 0x167b54        // CA::Layer::layout_if_needed(CA::Transaction*)
14  QuartzCore                          0x000000019be7f83c 0x19bd18000 + 0x16783c        // -[CALayer layoutIfNeeded]
15  Module_Framework                    0x00000001046dff14 0x1023d8000 + 0x2307f14       // func_2307ecc
16  Module_Framework                    0x00000001046a8df0 0x1023d8000 + 0x22d0df0       // func_22d0d1c
17  YouTube                             0x0000000100bc1d24 0x1006c0000 + 0x501d24        // func_501bf4
18  YouTube                             0x0000000100bbf758 0x1006c0000 + 0x4ff758        // func_4ff73c
19  YouTube                             0x0000000100c382fc 0x1006c0000 + 0x5782fc        // func_57823c
20  YouTube                             0x0000000100c36878 0x1006c0000 + 0x576878        // func_57685c
21  YouTube                             0x0000000100c3da1c 0x1006c0000 + 0x57da1c        // func_57d9d4
22  YouTube                             0x00000001008037c0 0x1006c0000 + 0x1437c0        // func_1433bc
23  YouTube                             0x0000000100ce404c 0x1006c0000 + 0x62404c        // func_623ee8
24  libdispatch.dylib                   0x00000001986b1a84 0x1986af000 + 0x2a84          // _dispatch_call_block_and_release
25  libdispatch.dylib                   0x00000001986b381c 0x1986af000 + 0x481c          // _dispatch_client_callout
26  libdispatch.dylib                   0x00000001986c1c70 0x1986af000 + 0x12c70         // _dispatch_main_queue_callback_4CF
27  CoreFoundation                      0x0000000198a40a2c 0x19899d000 + 0xa3a2c         // __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
28  CoreFoundation                      0x0000000198a3a904 0x19899d000 + 0x9d904         // __CFRunLoopRun
29  CoreFoundation                      0x0000000198a399f4 0x19899d000 + 0x9c9f4         // CFRunLoopRunSpecific
30  GraphicsServices                    0x00000001b010a734 0x1b0107000 + 0x3734          // GSEventRunModal
31  UIKitCore                           0x000000019b4b775c 0x19a8ed000 + 0xbca75c        // -[UIApplication _run]
32  UIKitCore                           0x000000019b4bcfcc 0x19a8ed000 + 0xbcffcc        // UIApplicationMain
33  YouTube                             0x00000001007474f0 0x1006c0000 + 0x874f0         // func_8745c
34  libdyld.dylib                       0x00000001986f5cf8 0x1986f4000 + 0x1cf8          // start

...

{"NSExceptionReason":"-[__NSFrozenArrayM insertObject:atIndex:]: unrecognized selector sent to instance 0x282289260","ProcessBundleID":"com.google.ios.youtube","ProcessName":"YouTube","Culprit":"YouMute.dylib"}
```

**Comment by PoomSmart** [comment]
It conflicts with YTKPlus.dylib - is that YouTubeKiller (plus) tweak?

**Comment by CySxL** [comment]
> It conflicts with YTKPlus.dylib - is that YouTubeKiller (plus) tweak?

Oh yeah it is. An advanced version called YTKillerPlus. I'll contact the dev also to see if he can fix this. Thanks !

**Comment by CySxL** [comment]
Fixed in 1.1.0, I have no clue why 😂😂

**Comment by arichornlover** [comment]
> Fixed in 1.1.0, I have no clue why 😂😂

v1.1.0 does break building though. Worked fine in v1.0.0 but probably arm64 did that 😂
```
> Making all in Tweaks/Return-YouTube-Dislikes…
[120](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:121)
> Making all for tweak YouTubeDislikesReturn…
[121](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:122)
==> Preprocessing Tweak.xm…
[122](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:123)
==> Compiling Tweak.xm (arm64)…
[123](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:124)
==> Linking tweak YouTubeDislikesReturn (arm64)…
[124](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:125)
==> Generating debug symbols for YouTubeDislikesReturn…
[125](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:126)
==> Stripping YouTubeDislikesReturn (arm64)…
[126](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:127)
==> Merging tweak YouTubeDislikesReturn…
[127](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:128)
==> Signing YouTubeDislikesReturn…
[128](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:129)
> Making all in Tweaks/YTABConfig…
[129](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:130)
> Making all for tweak YTABConfig…
[130](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:131)
==> Preprocessing Tweak.xm…
[131](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:132)
==> Compiling Tweak.xm (arm64)…
[132](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:133)
==> Linking tweak YTABConfig (arm64)…
[133](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:134)
==> Generating debug symbols for YTABConfig…
[134](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:135)
==> Stripping YTABConfig (arm64)…
[135](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:136)
==> Merging tweak YTABConfig…
[136](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:137)
==> Signing YTABConfig…
[137](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:138)
> Making all in Tweaks/YouMute…
[138](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:139)
> Making all for tweak YouMute…
[139](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:140)
==> Preprocessing Tweak.x…
[140](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:141)
==> Compiling Tweak.x (arm64)…
[141](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:142)
==> Linking tweak YouMute (arm64)…
[142](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:143)
Undefined symbols for architecture arm64:
[143](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:144)
  "_OBJC_CLASS_$_UIImage", referenced from:
[144](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:145)
      objc-class-ref in Tweak.x.78c1b9b0.o
[145](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:146)
ld: symbol(s) not found for architecture arm64
[146](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:147)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[147](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:148)
make[4]: *** [/Users/runner/work/uYouPlusExtra/uYouPlusExtra/main/.theos/obj/arm64/YouMute.dylib] Error 1
[148](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:149)
make[3]: *** [/Users/runner/work/uYouPlusExtra/uYouPlusExtra/main/.theos/obj/arm64/YouMute.dylib] Error 2
[149](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:150)
make[2]: *** [internal-library-all_] Error 2
[150](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:151)
make[1]: *** [YouMute.all.tweak.variables] Error 2
[151](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:152)
make: *** [internal-all] Error 2
```

**Comment by PoomSmart** [comment]
Irrelevant. That is just an issue with your build environment.

**Comment by arichornlover** [comment]
> Irrelevant. That is just an issue with your build environment.

Hmm, I did add `@cp -R Tweaks/YouMute/layout/Library/Application\ Support/YouMute.bundle Resources/` to it previously, guess I’ll find what else is causing it to do that

**Comment by CySxL** [comment]
> > Fixed in 1.1.0, I have no clue why 😂😂
> 
> 
> 
> v1.1.0 does break building though. Worked fine in v1.0.0 but probably arm64 did that 😂
> 
> ```
> 
> > Making all in Tweaks/Return-YouTube-Dislikes…
> 
> [120](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:121)
> 
> > Making all for tweak YouTubeDislikesReturn…
> 
> [121](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:122)
> 
> ==> Preprocessing Tweak.xm…
> 
> [122](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:123)
> 
> ==> Compiling Tweak.xm (arm64)…
> 
> [123](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:124)
> 
> ==> Linking tweak YouTubeDislikesReturn (arm64)…
> 
> [124](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:125)
> 
> ==> Generating debug symbols for YouTubeDislikesReturn…
> 
> [125](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:126)
> 
> ==> Stripping YouTubeDislikesReturn (arm64)…
> 
> [126](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:127)
> 
> ==> Merging tweak YouTubeDislikesReturn…
> 
> [127](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:128)
> 
> ==> Signing YouTubeDislikesReturn…
> 
> [128](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:129)
> 
> > Making all in Tweaks/YTABConfig…
> 
> [129](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:130)
> 
> > Making all for tweak YTABConfig…
> 
> [130](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:131)
> 
> ==> Preprocessing Tweak.xm…
> 
> [131](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:132)
> 
> ==> Compiling Tweak.xm (arm64)…
> 
> [132](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:133)
> 
> ==> Linking tweak YTABConfig (arm64)…
> 
> [133](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:134)
> 
> ==> Generating debug symbols for YTABConfig…
> 
> [134](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:135)
> 
> ==> Stripping YTABConfig (arm64)…
> 
> [135](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:136)
> 
> ==> Merging tweak YTABConfig…
> 
> [136](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:137)
> 
> ==> Signing YTABConfig…
> 
> [137](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:138)
> 
> > Making all in Tweaks/YouMute…
> 
> [138](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:139)
> 
> > Making all for tweak YouMute…
> 
> [139](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:140)
> 
> ==> Preprocessing Tweak.x…
> 
> [140](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:141)
> 
> ==> Compiling Tweak.x (arm64)…
> 
> [141](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:142)
> 
> ==> Linking tweak YouMute (arm64)…
> 
> [142](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:143)
> 
> Undefined symbols for architecture arm64:
> 
> [143](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:144)
> 
>   "_OBJC_CLASS_$_UIImage", referenced from:
> 
> [144](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:145)
> 
>       objc-class-ref in Tweak.x.78c1b9b0.o
> 
> [145](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:146)
> 
> ld: symbol(s) not found for architecture arm64
> 
> [146](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:147)
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> [147](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:148)
> 
> make[4]: *** [/Users/runner/work/uYouPlusExtra/uYouPlusExtra/main/.theos/obj/arm64/YouMute.dylib] Error 1
> 
> [148](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:149)
> 
> make[3]: *** [/Users/runner/work/uYouPlusExtra/uYouPlusExtra/main/.theos/obj/arm64/YouMute.dylib] Error 2
> 
> [149](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:150)
> 
> make[2]: *** [internal-library-all_] Error 2
> 
> [150](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:151)
> 
> make[1]: *** [YouMute.all.tweak.variables] Error 2
> 
> [151](https://github.com/arichorn/uYouPlusExtra/actions/runs/3596702684/jobs/6057665695#step:10:152)
> 
> make: *** [internal-all] Error 2
> 
> ```



Yeah literally with no idea since I tested with Choicy and three devices 😂😂

**Comment by arichornlover** [comment]
I did build the ipa with this error but crashes the app immediately

**Comment by arichornlover** [comment]
I resolved it. Used some sort of new environment
