### ISSUE TITLE
Crash on YT 19.26.5 - v1.2.2

### ISSUE THREAD

**Issue by peimingtai** [PoomSmart/YouMute#14]
Please fix it, it doesn't work on YT v19.26.5. I can't open the app

**Comment by PoomSmart** [comment]
Crash log?

I don't think it's YouMute that crashes the app because its latest update is to fix the crash on this exact YT version.

**Comment by peimingtai** [comment]
I only injected this 1 tweak and the app couldn't open, and the same method inject youtube-x works normally

**Comment by PoomSmart** [comment]
Crash log?

**Comment by peimingtai** [comment]
{"app_name":"YouTube","timestamp":"2024-07-06 14:20:10.00 +0700","app_version":"19.26.5","slice_uuid":"654fe0c5-ae11-3491-83d1-9e5daaeb50cd","build_version":"19.26.5","platform":2,"bundleID":"com.google.ios.youtube","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 17.5.1 (21F90)","roots_installed":0,"name":"YouTube","incident_id":"34A30AC4-7264-4B94-9F1A-FEDD2584563A"}
{
  "uptime" : 1000000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone13,4",
  "coalitionID" : 5596,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 17.5.1",
    "releaseType" : "User",
    "build" : "21F90"
  },
  "captureTime" : "2024-07-06 14:20:10.4434 +0700",
  "codeSigningMonitor" : 1,
  "incident" : "34A30AC4-7264-4B94-9F1A-FEDD2584563A",
  "pid" : 25108,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-07-06 14:20:09.9831 +0700",
  "procStartAbsTime" : 25591331858399,
  "procExitAbsTime" : 25591342897896,
  "procName" : "YouTube",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/9E3C3DD3-443B-4C55-87E8-2BBFA58440FF\/YouTube.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"19.26.5","CFBundleVersion":"19.26.5","CFBundleIdentifier":"com.google.ios.youtube","DTAppStoreToolsBuild":"15F31e"},
  "storeInfo" : {"deviceIdentifierForVendor":"63BBE1F4-2497-4EC1-ACE1-008D2AB9C33A","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.google.ios.youtube",
  "crashReporterKey" : "586ae432542c8122391de5f4e167dec88da7b0c5",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "codeSigningID" : "com.google.ios.youtube",
  "codeSigningTeamID" : "HGK8ZMN942",
  "codeSigningFlags" : 570434305,
  "codeSigningValidationCategory" : 5,
  "codeSigningTrustLevel" : 6,
  "instructionByteStream" : {"beforePC":"fyMD1f17v6n9AwCRNez\/l78DAJH9e8Go\/w9f1sADX9YQKYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkSrs\/5e\/AwCR\/XvBqP8PX9bAA1\/WECeA0g=="},
  "basebandVersion" : "4.50.06",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"YouTube","byPid":25108},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "exceptionReason" : {"arguments":["%s","%s","0x10d1c3788"],"format_string":"+[%s %s]: unrecognized selector sent to class %p","name":"NSInvalidArgumentException","type":"objc-exception","composed_message":"+[%s %s]: unrecognized selector sent to class 0x10d1c3788","class":"NSException"},
  "lastExceptionBacktrace" : [{"imageOffset":540448,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":9},{"imageOffset":90136,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":8},{"imageOffset":1626920,"symbol":"-[NSObject(NSObject) doesNotRecognizeSelector:]","symbolLocation":0,"imageIndex":9},{"imageOffset":135092,"symbol":"___forwarding___","symbolLocation":1572,"imageIndex":9},{"imageOffset":133328,"symbol":"_CF_forwarding_prep_0","symbolLocation":96,"imageIndex":9},{"imageOffset":17952,"imageIndex":1},{"imageOffset":100708,"symbol":"invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const","symbolLocation":168,"imageIndex":10},{"imageOffset":73664,"symbol":"invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":172,"imageIndex":10},{"imageOffset":11400,"symbol":"invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":496,"imageIndex":10},{"imageOffset":7752,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":300,"imageIndex":10},{"imageOffset":107016,"symbol":"dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":192,"imageIndex":10},{"imageOffset":54744,"symbol":"dyld3::MachOFile::forEachInitializerPointerSection(Diagnostics&, void (unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":160,"imageIndex":10},{"imageOffset":54288,"symbol":"dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":432,"imageIndex":10},{"imageOffset":52780,"symbol":"dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const","symbolLocation":524,"imageIndex":10},{"imageOffset":60284,"symbol":"dyld4::JustInTimeLoader::runInitializers(dyld4::RuntimeState&) const","symbolLocation":36,"imageIndex":10},{"imageOffset":50112,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":220,"imageIndex":10},{"imageOffset":50020,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":128,"imageIndex":10},{"imageOffset":77552,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const","symbolLocation":116,"imageIndex":10},{"imageOffset":76928,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const","symbolLocation":380,"imageIndex":10},{"imageOffset":4832,"symbol":"dyld4::APIs::runAllInitializersForMain()","symbolLocation":336,"imageIndex":10},{"imageOffset":98980,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3328,"imageIndex":10},{"imageOffset":248904,"symbol":"start","symbolLocation":1724,"imageIndex":10}],
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":13902191,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":8144081603},{"value":6101001232},{"value":110},{"value":0},{"value":6628862790370159864},{"value":6628862797230182968},{"value":512},{"value":6101000000},{"value":0},{"value":2095104},{"value":16},{"value":0},{"value":328},{"value":8210644672,"symbolLocation":0,"symbol":"_main_thread"},{"value":0},{"value":6},{"value":259},{"value":8210644896,"symbolLocation":224,"symbol":"_main_thread"},{"value":12903027528},{"value":1},{"value":1},{"value":104},{"value":6101005536},{"value":4526540288},{"value":6101038504}],"flavor":"ARM_THREAD_STATE64","lr":{"value":8144989196},"cpsr":{"value":1073745920},"fp":{"value":6101001088},"sp":{"value":6101001056},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7811937324,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":50220,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":4},{"imageOffset":31756,"symbol":"pthread_kill","symbolLocation":268,"imageIndex":5},{"imageOffset":482208,"symbol":"abort","symbolLocation":180,"imageIndex":6},{"imageOffset":85156,"symbol":"abort_message","symbolLocation":132,"imageIndex":7},{"imageOffset":20060,"symbol":"demangling_terminate_handler()","symbolLocation":348,"imageIndex":7},{"imageOffset":204332,"symbol":"_objc_terminate()","symbolLocation":144,"imageIndex":8},{"imageOffset":82024,"symbol":"std::__terminate(void (*)())","symbolLocation":16,"imageIndex":7},{"imageOffset":95068,"symbol":"__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)","symbolLocation":88,"imageIndex":7},{"imageOffset":94880,"symbol":"__cxa_throw","symbolLocation":308,"imageIndex":7},{"imageOffset":90496,"symbol":"objc_exception_throw","symbolLocation":420,"imageIndex":8},{"imageOffset":1626920,"symbol":"+[NSObject(NSObject) doesNotRecognizeSelector:]","symbolLocation":344,"imageIndex":9},{"imageOffset":135092,"symbol":"___forwarding___","symbolLocation":1572,"imageIndex":9},{"imageOffset":133328,"symbol":"_CF_forwarding_prep_0","symbolLocation":96,"imageIndex":9},{"imageOffset":17952,"imageIndex":1},{"imageOffset":100708,"symbol":"invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const","symbolLocation":168,"imageIndex":10},{"imageOffset":73664,"symbol":"invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":172,"imageIndex":10},{"imageOffset":11400,"symbol":"invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":496,"imageIndex":10},{"imageOffset":7752,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":300,"imageIndex":10},{"imageOffset":107016,"symbol":"dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":192,"imageIndex":10},{"imageOffset":54744,"symbol":"dyld3::MachOFile::forEachInitializerPointerSection(Diagnostics&, void (unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":160,"imageIndex":10},{"imageOffset":54288,"symbol":"dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":432,"imageIndex":10},{"imageOffset":52780,"symbol":"dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const","symbolLocation":524,"imageIndex":10},{"imageOffset":60284,"symbol":"dyld4::JustInTimeLoader::runInitializers(dyld4::RuntimeState&) const","symbolLocation":36,"imageIndex":10},{"imageOffset":50112,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":220,"imageIndex":10},{"imageOffset":50020,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":128,"imageIndex":10},{"imageOffset":77552,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const","symbolLocation":116,"imageIndex":10},{"imageOffset":76928,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const","symbolLocation":380,"imageIndex":10},{"imageOffset":4832,"symbol":"dyld4::APIs::runAllInitializersForMain()","symbolLocation":336,"imageIndex":10},{"imageOffset":98980,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3328,"imageIndex":10},{"imageOffset":248904,"symbol":"start","symbolLocation":1724,"imageIndex":10}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4537352192,
    "size" : 1245184,
    "uuid" : "509fdab7-cedf-3fc3-81e1-ccfd6ce62f36",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/9E3C3DD3-443B-4C55-87E8-2BBFA58440FF\/YouTube.app\/Frameworks\/widevine_cdm_secured_ios.framework\/widevine_cdm_secured_ios",
    "name" : "widevine_cdm_secured_ios"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4526538752,
    "size" : 32768,
    "uuid" : "a953eec3-8b84-34c8-a7d4-6ef91c12986a",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/9E3C3DD3-443B-4C55-87E8-2BBFA58440FF\/YouTube.app\/Frameworks\/YouMute.dylib",
    "name" : "YouMute.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4526637056,
    "size" : 1245184,
    "uuid" : "486eb8c2-09c9-3e0f-82ab-6cd0afbe4326",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/9E3C3DD3-443B-4C55-87E8-2BBFA58440FF\/YouTube.app\/Frameworks\/CydiaSubstrate.framework\/CydiaSubstrate",
    "name" : "CydiaSubstrate"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4365844480,
    "size" : 131186688,
    "uuid" : "459fe0c5-ae11-3491-83d1-9e5daaeb50cd",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/9E3C3DD3-443B-4C55-87E8-2BBFA58440FF\/YouTube.app\/YouTube",
    "name" : "YouTube"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7811887104,
    "size" : 237552,
    "uuid" : "13b5134e-819c-3baa-b300-4856112114cb",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8144957440,
    "size" : 53236,
    "uuid" : "1196b6c3-333d-3450-818f-f3663484b8eb",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6719508480,
    "size" : 516084,
    "uuid" : "b122f07f-a156-37f3-a22d-64627c0c4b24",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8143978496,
    "size" : 114684,
    "uuid" : "f603d156-e9c5-3563-80a6-d2ebedc07a02",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6450741248,
    "size" : 319300,
    "uuid" : "53115e1f-e353-30d9-9e8a-4e6e73489f05",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6585896960,
    "size" : 5431296,
    "uuid" : "00e76a98-210c-3cb5-930b-f236807ff24c",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7180210176,
    "size" : 577272,
    "uuid" : "71846eac-ee65-3697-bf7d-790b6a07dcdb",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6449790976,
  "size" : 3682713600,
  "uuid" : "4ec6c7ac-7777-376b-96aa-5587cdd663b7"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)\nWritable regions: Total=542.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=542.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           535.2M       23 \nMALLOC guard page                   64K        4 \nSMOOTH                               24        2 \nSTACK GUARD                         16K        1 \nStack                             1008K        1 \n__AUTH                            3184K      368 \n__AUTH_CONST                      38.0M      834 \n__CTF                               824        1 \n__DATA                            53.0M      832 \n__DATA_CONST                      49.2M      842 \n__DATA_DIRTY                      10.3M      790 \n__ETC                              112K        1 \n__FONT_DATA                          4K        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       390.4M        5 \n__OBJC_RO                         86.6M        1 \n__OBJC_RW                         2754K        1 \n__TEXT                             1.1G      855 \ndyld private memory               5408K        4 \nmapped file                         64K        1 \nshared memory                       48K        2 \n===========                     =======  ======= \nTOTAL                              2.2G     4572 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "65e02d3904c92d61badcd1c5d7c4b27055b7662e",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6410af69ed1e1e7ab93ed169",
      "factorPackIds" : {
        "SIRI_VALUE_INFERENCE_PHONECALL_SMART_APP_SELECTION" : "65bc2fba99e56d0d1953c5e5"
      },
      "deploymentId" : 240000011
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "b42c55f8-c6ce-492a-b759-34a011c28942",
      "experimentId" : "65c3fcf195b5e23d93cddb1e",
      "deploymentId" : 400000006
    },
    {
      "treatmentId" : "3dff9c91-a8fb-424e-a656-c8d6e6037574",
      "experimentId" : "662152ede2d11d1408c4db33",
      "deploymentId" : 400000016
    }
  ]
}
}

**Comment by PoomSmart** [comment]
Sideloaded YT there, and you have to inject YTVideoOverlay tweak too.

**Comment by peimingtai** [comment]
Thanks for your help I did it
